[metadata]
name = sasci360solplanning
version = 0.0.1
author = Nelson Grey LLC
author_email = support@nelsongrey.com
description = Python interfaces for SAS Customer Intelligence 360 Planning APIs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mnelson3/sas-ci360-sol-planning
project_urls = Bug Tracker = https://github.com/mnelson3/sas-ci360-sol-planning/issues
classifiers = Programming Language :: Python :: 3
	License :: Other/Proprietary License
	Operating System :: OS Independent

[options]
package_dir = = src
packages = find:
python_requires = >=3.8
install_requires =
	pandas>=2.0.0
	PyJWT>=2.0.0
	requests>=2.31.0
	saspy>=5.0.0
	schedule>=1.1.0
	DateTime>=4.3
	urllib3>=2.0.0

[options.packages.find]
where = src
